# cloudbuild.yaml for Deliberate Lab Backend Deployments

substitutions:
  _DEPLOYMENT_TYPE: 'test' # Default value, will be overridden by triggers (test, functions, rules, indexes, all)

options:
  logging: CLOUD_LOGGING_ONLY
  automapSubstitutions: true

steps:
# 0. Install Dependencies
- name: 'node:22'
  id: NpmCI
  script: |
    #!/usr/bin/env bash
    set -e
    echo "Node version:"
    node -v
    echo "NPM version:"
    npm -v
    echo "Installing dependencies..."
    npm ci
  dir: '.'

# 1. Lint & Format Check
- name: 'node:22'
  id: LintCheck
  script: |
    #!/usr/bin/env bash
    set -e
    if [[ "${_DEPLOYMENT_TYPE}" == "functions" || "${_DEPLOYMENT_TYPE}" == "test" || "${_DEPLOYMENT_TYPE}" == "all" ]]; then
      echo "Running Lint/Format Check..."
      # Scoped to backend directories to avoid blocking on frontend issues
      npx prettier --check "functions/**/*.ts" "utils/**/*.ts"
      npx eslint --quiet "functions/**/*.ts" "utils/**/*.ts"
    else
      echo "Skipping Lint/Format Check for '${_DEPLOYMENT_TYPE}' deployment."
    fi
  waitFor: ['NpmCI']
  dir: '.'

# 2. Build Utils Workspace
- name: 'node:22'
  id: BuildUtils
  script: |
    #!/usr/bin/env bash
    set -e
    if [[ "${_DEPLOYMENT_TYPE}" == "functions" || "${_DEPLOYMENT_TYPE}" == "test" || "${_DEPLOYMENT_TYPE}" == "all" ]]; then
      echo "Building utils workspace..."
      npm run build --workspace=utils
    else
      echo "Skipping Build Utils for '${_DEPLOYMENT_TYPE}' deployment."
    fi
  waitFor: ['LintCheck']
  dir: '.'

# 3. Build Functions Workspace
- name: 'node:22'
  id: BuildFunctions
  script: |
    #!/usr/bin/env bash
    set -e
    if [[ "${_DEPLOYMENT_TYPE}" == "functions" || "${_DEPLOYMENT_TYPE}" == "test" || "${_DEPLOYMENT_TYPE}" == "all" ]]; then
      echo "Building functions workspace..."
      npm run build --workspace=functions
    else
      echo "Skipping Build Functions for '${_DEPLOYMENT_TYPE}' deployment."
    fi
  waitFor: ['BuildUtils']
  dir: '.'

# 4. Run Tests (Install Java 21 for functions tests)
- name: 'node:22'
  id: TestFunctions
  script: |
    #!/usr/bin/env bash
    set -e
    if [[ "${_DEPLOYMENT_TYPE}" == "functions" || "${_DEPLOYMENT_TYPE}" == "test" || "${_DEPLOYMENT_TYPE}" == "all" ]]; then
      echo "Installing Oracle JDK 21..."
      apt-get update -y && apt-get install -y wget
      wget -q https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb
      apt-get install -y ./jdk-21_linux-x64_bin.deb
      rm jdk-21_linux-x64_bin.deb
      export JAVA_HOME=/usr/lib/jvm/jdk-21-oracle-x64
      export PATH=$JAVA_HOME/bin:$PATH
      echo "Java version check:"
      java -version

      echo "Running Backend Tests..."
      npm test --workspace=utils
      npm test --workspace=functions
    else
      echo "Skipping Tests for '${_DEPLOYMENT_TYPE}' deployment."
    fi
  waitFor: ['BuildFunctions']
  dir: '.'

# 5. Deploy Functions Step
- name: 'node:22'
  id: DeployFirebaseFunctions
  script: |
    #!/usr/bin/env bash
    set -e
    echo "Deployment Type: '${_DEPLOYMENT_TYPE}'"

    if [[ "${_DEPLOYMENT_TYPE}" == "functions" ]]; then
      echo "Deploying Functions..."
      npx firebase deploy --only functions --project ${PROJECT_ID} --no-predeploy --non-interactive --force
    else
      echo "Skipping backend deploy for '${_DEPLOYMENT_TYPE}' deployment."
    fi
  waitFor: ['TestFunctions']
  dir: '.'

# 6. Deploy Rules Step
- name: 'node:22'
  id: DeployFirebaseRules
  script: |
    #!/usr/bin/env bash
    set -e
    echo "Deployment Type: '${_DEPLOYMENT_TYPE}'"

    if [[ "${_DEPLOYMENT_TYPE}" == "rules" ]]; then
      echo "Deploying Rules (Firestore, Database)..."
      npx firebase deploy --only firestore:rules,database:rules --project ${PROJECT_ID} --non-interactive --force
    else
      echo "Skipping Firebase rules deploy for '${_DEPLOYMENT_TYPE}' deployment."
    fi
  waitFor: ['NpmCI']
  dir: '.'

# 7. Deploy Indexes Step
- name: 'node:22'
  id: DeployFirebaseIndexes
  script: |
    #!/usr/bin/env bash
    set -e
    echo "Deployment Type: '${_DEPLOYMENT_TYPE}'"

    if [[ "${_DEPLOYMENT_TYPE}" == "indexes" ]]; then
      echo "Deploying Firestore Indexes..."
      npx firebase deploy --only firestore:indexes --project ${PROJECT_ID} --non-interactive --force
    else
      echo "Skipping Firebase indexes deploy for '${_DEPLOYMENT_TYPE}' deployment."
    fi
  waitFor: ['NpmCI']
  dir: '.'
