/** Profile sets to use for anonymous profiles. */

/** First set of animals. */
export const PROFILE_SET_ANIMALS_1: {name: string, avatar: string}[] = 
[
  {name: 'Alligator', avatar: '🐊'},
  {name: 'Bear', avatar: '🐻'},
  {name: 'Bat', avatar: '🦇'},
  {name: 'Buffalo', avatar: '🐃'},
  {name: 'Butterfly', avatar: '🦋'},
  {name: 'Badger', avatar: '🦡'},
  {name: 'Camel', avatar: '🐪'},
  {name: 'Cat', avatar: '🐱'},
  {name: 'Dog', avatar: '🐶'},
  {name: 'Dolphin', avatar: '🐬'},
  {name: 'Duck', avatar: '🦆'},
  {name: 'Elephant', avatar: '🐘'},
  {name: 'Frog', avatar: '🐸'},
  {name: 'Fox', avatar: '🦊'},
  {name: 'Goose', avatar: '🪿'},
  {name: 'Gorilla', avatar: '🦍'},
  {name: 'Hedgehog', avatar: '🦔'},
  {name: 'Hamster', avatar: '🐹'},
  {name: 'Iguana', avatar: '🦎'},
  {name: 'Kangaroo', avatar: '🦘'},
  {name: 'Lion', avatar: '🦁'},
  {name: 'Llama', avatar: '🦙'},
  {name: 'Monkey', avatar: '🐵'},
  {name: 'Mouse', avatar: '🐭'},
  {name: 'Octopus', avatar: '🐙'},
  {name: 'Owl', avatar: '🦉'},
  {name: 'Otter', avatar: '🦦'},
  {name: 'Parrot', avatar: '🦜'},
  {name: 'Peacock', avatar: '🦚'},
  {name: 'Pig', avatar: '🐷'},
  {name: 'Rabbit', avatar: '🐰'},
  {name: 'Ram', avatar: '🐏'},
  {name: 'Swan', avatar: '🦢'},
  {name: 'Squid', avatar: '🦑'},
  {name: 'Snail', avatar: '🐌'},
  {name: 'Turtle', avatar: '🐢'},
  {name: 'Tiger', avatar: '🐯'},
  {name: 'Unicorn', avatar: '🦄'},
  {name: 'Whale', avatar: '🐳'},
  {name: 'Zebra', avatar: '🦓'}
];

/* Second set of animals. */
export const PROFILE_SET_ANIMALS_2: {name: string, avatar: string}[] = 
[
  {name: 'Beaver', avatar: '🦫'},
  {name: 'Blowfish', avatar: '🐡'},
  {name: 'Bison', avatar: '🦬'},
  {name: 'Boar', avatar: '🐗'},
  {name: 'Caterpillar', avatar: '🐛'},
  {name: 'Chicken', avatar: '🐔'},
  {name: 'Chipmunk', avatar: '🐿️'},
  {name: 'Cow', avatar: '🐮'},
  {name: 'Deer', avatar: '🦌'},
  {name: 'Dragon', avatar: '🐉'},
  {name: 'Donkey', avatar: '🫏'},
  {name: 'Eagle', avatar: '🦅'},
  {name: 'Ewe', avatar: '🐑'},
  {name: 'Flamingo', avatar: '🦩'},
  {name: 'Giraffe', avatar: '🦒'},
  {name: 'Goat', avatar: '🐐'},
  {name: 'Hippopotamus', avatar: '🦛'},
  {name: 'Honeybee', avatar: '🐝'},
  {name: 'Horse', avatar: '🐴'},
  {name: 'Jellyfish', avatar: '🪼'},
  {name: 'Koala', avatar: '🐨'},
  {name: 'Lobster', avatar: '🦞'},
  {name: 'Leopard', avatar: '🐆'},
  {name: 'Ladybug', avatar: '🐞'},
  {name: 'Moose', avatar: '🫎'},
  {name: 'Mammoth', avatar: '🦣'},
  {name: 'Nightingale', avatar: '🐦'},
  {name: 'Orangutan', avatar: '🦧'},
  {name: 'Panda', avatar: '🐼'},
  {name: 'Penguin', avatar: '🐧'},
  {name: 'Phoenix', avatar: '🐦‍🔥'},
  {name: 'Raccoon', avatar: '🦝'},
  {name: 'Rhinoceros', avatar: '🦏'},
  {name: 'Seal', avatar: '🦭'},
  {name: 'Shark', avatar: '🦈'},
  {name: 'Shrimp', avatar: '🦐'},
  {name: 'Tuna', avatar: '🐟'},
  {name: 'Turkey', avatar: '🦃'},
  {name: 'Unau', avatar: '🦥'},
  {name: 'Wolf', avatar: '🐺'}
];

/** Nature set with flowers, rocks, etc. */
export const PROFILE_SET_NATURE: {name: string, avatar: string}[] =
[
  {name: 'Amber', avatar: '🍯'},
  {name: 'Amethyst', avatar: '🔮'},
  {name: 'Breeze', avatar: '🌬️'},
  {name: 'Blossom', avatar: '🌸'},
  {name: 'Citrus', avatar: '🍋'},
  {name: 'Cloud', avatar: '☁️'},
  {name: 'Cactus', avatar: '🌵'},
  {name: 'Coral', avatar: '🪸'},
  {name: 'Daisy', avatar: '🌼'},
  {name: 'Desert', avatar: '🏜️'},
  {name: 'Frost', avatar: '❄️'},
  {name: 'Forest', avatar: '🌲'},
  {name: 'Glacier', avatar: '🧊'},
  {name: 'Garnet', avatar: '🌰'},
  {name: 'Grove', avatar: '🌳'},
  {name: 'Halite', avatar: '🧂'},
  {name: 'Hyacinth', avatar: '🪻'},
  {name: 'Hibiscus', avatar: '🌺'},
  {name: 'Island', avatar: '🏝️'},
  {name: 'Jade', avatar: '🥬'},
  {name: 'Lava', avatar: '🌋'},
  {name: 'Leaf', avatar: '🍃'},
  {name: 'Lightning', avatar: '⚡'},
  {name: 'Marble', avatar: '♟️'},
  {name: 'Mountain', avatar: '⛰️'},
  {name: 'Mushroom', avatar: '🍄'},
  {name: 'Maple', avatar: '🍁'},
  {name: 'Moonstone', avatar: '🌙'},
  {name: 'Obsidian', avatar: '🐈‍⬛'},
  {name: 'Onyx', avatar: '🪨'},
  {name: 'Opal', avatar: '🫧'},
  {name: 'Quartz', avatar: '💎'},
  {name: 'Rose', avatar: '🌹'},
  {name: 'Sandstone', avatar: '🧱'},
  {name: 'Sapphire', avatar: '🌊'},
  {name: 'Sunstone', avatar: '☀️'},
  {name: 'Sunflower', avatar: '🌻'},
  {name: 'Seashell', avatar: '🐚'},
  {name: 'Tulip', avatar: '🌷'},
  {name: 'Wisteria', avatar: '💐'}
];
